version: '3.7'
services:
  mysql:
    container_name: "apiapp_mysql"
    image: mysql:5.7
    restart: always
    volumes:
      - ./container_config/mysql/migrations/:/docker-entrypoint-initdb.d:delegated
      - "sql_vol:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: apiservice
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
        TZ: 'America/Sao_Paulo'
volumes:
    sql_vol:
        driver: local
